name: Run E2E testing
description: Encapsulated step for E2E testing

inputs:
  config-file:
    description: "Relative E2E configuration file path(base path: ./test/e2e/cases/)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build docker images for E2E testing
      uses: ./.github/build-for-e2e

    - name: Run E2E testing
      uses: apache/skywalking-infra-e2e@v1.1.0
      env:
        K8S_VERSION: ${{ matrix.k8sVersion }}
      with:
        e2e-file: ./test/e2e/cases/${{ inputs.config-file }}
